import turtle

def draw_K(t):
    t.penup()
    t.goto(-200,0)
    t.pendown()
    t.color("pink")
    t.pensize(20)
    t.left(90)
    t.forward(100)
    t.backward(50)
    t.right(45)
    t.forward(70)
    t.backward(70)
    t.right(90)
    t.forward(70)
    t.backward(70)
    t.right(45)
    t.forward(50)
    t.end_fill()
    t.left(90)
    t.end_fill()
    t.penup()
    t.home()

def draw_E(t):
    t.penup()
    t.goto(-100,60)
    t.pendown()
    t.color("pink")
    t.pensize(20)
    t.forward(50)
    t.backward(50)
    t.right(90)
    t.forward(30)
    t.left(90)
    t.forward(50)
    t.backward(50)
    t.right(90)
    t.forward(30)
    t.left(90)
    t.forward(50)
    t.end_fill()
    t.penup()
    t.home()

def draw_V(t):
    t.penup()
    t.goto(0,0)
    t.pendown()
    t.pensize(20)
    t.right(30)
    t.forward(100)
    t.left(120)
    t.forward(100)
    t.left(180)
    t.forward(50)
    t.right(120)
    
    t.end_fill()
    t.right(30)
    t.end_fill()
    t.penup()
    t.home()

def draw_S(t):
    t.penup()
    t.goto(100,0)
    t.pendown()
    t.pensize(20)
    t.right(45)
    t.circle(30, 180)
    t.circle(-30, 180)
    t.end_fill()
    t.end_fill()
    t.penup()
    t.home()

def draw_E2(t):
    t.penup()
    t.goto(200,60)
    t.pendown()
    t.color("pink")
    t.pensize(20)
    t.forward(50)
    t.backward(50)
    t.right(90)
    t.forward(30)
    t.left(90)
    t.forward(50)
    t.backward(50)
    t.right(90)
    t.forward(30)
    t.left(90)
    t.forward(50)
    t.end_fill()
    t.penup()
    t.home()
    
def draw_R(t):
    t.penup()
    t.goto(300,60)
    t.pendown()
    t.pensize(20)
    t.left(90)
    t.forward(100)
    t.right(90)
    t.circle(-25, 180)
    t.left(90)
    
    t.left(45)
    t.forward(70)
    t.end_fill()
    t.left(45)
    t.end_fill()
    t.penup()
    t.home()

def main():
    screen = turtle.Screen()
    t = turtle.Turtle()

    draw_K(t)
    draw_E(t)
    draw_V(t)
    draw_S(t)
    draw_E2(t)
    draw_R(t)

    screen.mainloop()

if __name__ == "__main__":
    main()
