message='Hello There. My Name İs Kevser Farımaz'
#message =message.upper()
#message=message.lower()
#message = message.title()
#message=message.capitalize()
#message = message.strip()
#message=message.split('.')
#message='*'.join(message)
# message='---'.join(message)
# index=message.find('Kevser')
# isFound=message.startswith('H')
#isFound=message.endswith('n)
message=message.replace('Kevser','Farımaz')                
message=message.replace('e','E')
message=message.replace('a','k')
message=message.replace(' ','*')

print(message)
#print(message[2]) 